### ISSUE TITLE
Form submission edit page - undefined variables `$data` in ninja-forms/includes/fields/list.php

### ISSUE THREAD

**Issue by smypf** [wpninjas/ninja-forms#940]
I've experienced a couple of issues when trying to view submission details.

```
Unhandled Exception

Message:
Undefined variable: data
Location:
/var/www/basesite/htdocs/content/plugins/ninja-forms/includes/fields/list.php on line 748
Stack Trace:
#0 /var/www/basesite/htdocs/content/themes/themeosis-theme/functions.php(232): Themosis\Error\Error::native(8, 'Undefined varia...', '/var/www/basesi...', 748)
#1 /var/www/basesite/htdocs/content/plugins/ninja-forms/includes/fields/list.php(748): {closure}(8, 'Undefined varia...', '/var/www/basesi...', 748, Array)
#2 [internal function]: nf_field_list_edit_sub_value(9, 'Option 2', Array, '715')
#3 /var/www/basesite/htdocs/content/plugins/ninja-forms/classes/subs-cpt.php(939): call_user_func_array('nf_field_list_e...', Array)
#4 [internal function]: NF_Subs_CPT->edit_sub_metabox(Object(WP_Post), Array)
#5 /var/www/basesite/htdocs/cms/wp-admin/includes/template.php(1090): call_user_func(Array, Object(WP_Post), Array)
#6 /var/www/basesite/htdocs/cms/wp-admin/edit-form-advanced.php(627): do_meta_boxes(NULL, 'normal', Object(WP_Post))
#7 /var/www/basesite/htdocs/cms/wp-admin/post.php(218): include('/var/www/basesi...')
#8 {main}
```

Changing the code to what's in the linked patch remedies this problem, but I'm not sure if this is the solution to the problem or just a bandaid solution.

https://gist.github.com/smypf/fda67bb6d3aa3352ff81

**Comment by jameslaws** [comment]
Can this be confirmed in 3.0?

**Comment by kstover** [comment]
Closing for lack of feedback.
